name: Deploy to production via FTP
on:
  push:
    branches:
      - production
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy_ftp:
    name: deploy_ftp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Sync files to production server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.your-production-server.com
          username: your_production_username
          password: ${{ secrets.PRODUCTION_FTP_PASSWORD }}
          server-dir: /public_html/production/
          local-dir: dist/
